const crypto=require('node:crypto');const{getProductionStore}=require('../persistence/production_store');
async function schema(){const s=await getProductionStore();if(!s)throw new Error('DATABASE_NOT_CONFIGURED');await s.pool.query(`ALTER TABLE bos_users ADD COLUMN IF NOT EXISTS email_verified_at TIMESTAMPTZ;CREATE TABLE IF NOT EXISTS bos_auth_tokens(id TEXT PRIMARY KEY,user_id TEXT NOT NULL REFERENCES bos_users(id) ON DELETE CASCADE,type TEXT NOT NULL,token_hash TEXT NOT NULL UNIQUE,expires_at TIMESTAMPTZ NOT NULL,used_at TIMESTAMPTZ,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());CREATE INDEX IF NOT EXISTS bos_auth_tokens_lookup_idx ON bos_auth_tokens(token_hash,type,expires_at);`);return s;}
const hash=t=>crypto.createHash('sha256').update(t).digest('hex');const makeToken=()=>crypto.randomBytes(32).toString('base64url');
async function issue(userId,type){const s=await schema(),token=makeToken();await s.pool.query(`UPDATE bos_auth_tokens SET used_at=NOW() WHERE user_id=$1 AND type=$2 AND used_at IS NULL`,[userId,type]);await s.pool.query(`INSERT INTO bos_auth_tokens(id,user_id,type,token_hash,expires_at) VALUES($1,$2,$3,$4,NOW()+($5||' hours')::interval)`,[`auth_${crypto.randomUUID()}`,userId,type,hash(token),type==='verification'?24:1]);return token;}
async function sendEmail({to,subject,html}){const key=String(process.env.RESEND_API_KEY||'').trim(),from=String(process.env.BOS_EMAIL_FROM||'').trim();if(!key||!from)return{sent:false,reason:'EMAIL_PROVIDER_NOT_CONFIGURED'};const r=await fetch('https://api.resend.com/emails',{method:'POST',headers:{authorization:`Bearer ${key}`,'content-type':'application/json'},body:JSON.stringify({from,to,subject,html})});if(!r.ok)return{sent:false,reason:'EMAIL_PROVIDER_FAILED',status:r.status};return{sent:true};}
async function requestVerification(user){const token=await issue(user.id,'verification');const base=String(process.env.BOS_APP_URL||'').replace(/\/$/,'');return sendEmail({to:user.email,subject:'Verify your BOS email',html:`<p>Welcome to BOS.</p><p><a href="${base}/verify-email?token=${encodeURIComponent(token)}">Verify your email</a></p>`});}
async function verifyEmail(token){const s=await schema(),r=await s.pool.query(`SELECT id,user_id FROM bos_auth_tokens WHERE token_hash=$1 AND type='verification' AND used_at IS NULL AND expires_at>NOW()`,[hash(token)]);if(!r.rowCount)throw new Error('VERIFICATION_TOKEN_INVALID');await s.pool.query('UPDATE bos_users SET email_verified_at=NOW() WHERE id=$1',[r.rows[0].user_id]);await s.pool.query('UPDATE bos_auth_tokens SET used_at=NOW() WHERE id=$1',[r.rows[0].id]);return{verified:true};}
async function requestPasswordReset(email){const s=await schema(),r=await s.pool.query('SELECT id,email,name FROM bos_users WHERE email=$1',[String(email||'').trim().toLowerCase()]);if(!r.rowCount)return{accepted:true};const user=r.rows[0],token=await issue(user.id,'password_reset'),base=String(process.env.BOS_APP_URL||'').replace(/\/$/,'');return sendEmail({to:user.email,subject:'Reset your BOS password',html:`<p>Reset your BOS password.</p><p><a href="${base}/reset-password?token=${encodeURIComponent(token)}">Reset password</a></p><p>This link expires in 1 hour.</p>`});}
async function resetPassword(token,newPassword){if(String(newPassword||'').length<8)throw new Error('PASSWORD_MIN_8');const s=await schema(),r=await s.pool.query(`SELECT id,user_id FROM bos_auth_tokens WHERE token_hash=$1 AND type='password_reset' AND used_at IS NULL AND expires_at>NOW()`,[hash(token)]);if(!r.rowCount)throw new Error('RESET_TOKEN_INVALID');const salt=crypto.randomBytes(16).toString('hex'),encoded=await new Promise((resolve,reject)=>crypto.scrypt(String(newPassword),salt,64,{N:16384,r:8,p:1},(e,d)=>e?reject(e):resolve(`scrypt$${salt}$${d.toString('hex')}`)));await s.pool.query('BEGIN');try{await s.pool.query('UPDATE bos_users SET password_hash=$1 WHERE id=$2',[encoded,r.rows[0].user_id]);await s.pool.query('UPDATE bos_auth_tokens SET used_at=NOW() WHERE id=$1',[r.rows[0].id]);await s.pool.query('DELETE FROM bos_sessions WHERE user_id=$1',[r.rows[0].user_id]);await s.pool.query('COMMIT');}catch(e){await s.pool.query('ROLLBACK');throw e}return{reset:true};}
module.exports={requestVerification,verifyEmail,requestPasswordReset,resetPassword};
