const assert=require('node:assert/strict');const test=require('node:test');const http=require('node:http');const {requestHandler}=require('../server');
function request(url){return new Promise((resolve,reject)=>{const server=http.createServer(requestHandler).listen(0,()=>{const port=server.address().port;const req=http.get(`http://127.0.0.1:${port}${url}`,res=>{let body='';res.setEncoding('utf8');res.on('data',chunk=>{body+=chunk});res.on('end',()=>{server.close();resolve({statusCode:res.statusCode,contentType:res.headers['content-type'],body})})});req.on('error',error=>{server.close();reject(error)})})})}
function post(url,payload,headers={}){return new Promise((resolve,reject)=>{const server=http.createServer(requestHandler).listen(0,()=>{const port=server.address().port;const body=JSON.stringify(payload);const req=http.request(`http://127.0.0.1:${port}${url}`,{method:'POST',headers:{'content-type':'application/json','content-length':Buffer.byteLength(body),...headers}},res=>{let responseBody='';res.setEncoding('utf8');res.on('data',chunk=>{responseBody+=chunk});res.on('end',()=>{server.close();resolve({statusCode:res.statusCode,contentType:res.headers['content-type'],body:responseBody})})});req.on('error',error=>{server.close();reject(error)});req.end(body)})})}
test('serves customer dashboard',async()=>{const response=await request('/dashboard');assert.equal(response.statusCode,200);assert.match(response.contentType,/text\/html/);assert.match(response.body,/Business Workspace/);assert.match(response.body,/BOS/)})
test('serves dashboard API health endpoint',async()=>{const response=await request('/api/health');assert.equal(response.statusCode,200);assert.match(response.contentType,/application\/json/);assert.deepEqual(JSON.parse(response.body).status,'ok')})
test('dashboard exposes business workspace onboarding controls',async()=>{const response=await request('/dashboard');assert.equal(response.statusCode,200);assert.match(response.body,/Create your workspace/);assert.match(response.body,/businessName/);assert.match(response.body,/industry/);assert.match(response.body,/teamSize/);assert.match(response.body,/workspaceForm/)})
test('serves workflow builder with core workflow controls',async()=>{const response=await request('/workflows');assert.equal(response.statusCode,200);assert.match(response.contentType,/text\/html/);assert.match(response.body,/BOS Workflow Builder/);assert.match(response.body,/Workflow name/);assert.match(response.body,/Choose a trigger/);assert.match(response.body,/Choose an action/);assert.match(response.body,/Run workflow/);assert.match(response.body,/workflow/)})
test('serves AI employee configuration with governance controls',async()=>{const response=await request('/ai-employees');assert.equal(response.statusCode,200);assert.match(response.contentType,/text\/html/);assert.match(response.body,/BOS AI Employees/);assert.match(response.body,/Employee name/);assert.match(response.body,/Objective/);assert.match(response.body,/Require approval for high-risk actions/);assert.match(response.body,/Record execution activity for audit/)})
test('serves integration connection surface',async()=>{const response=await request('/integrations');assert.equal(response.statusCode,200);assert.match(response.contentType,/text\/html/);assert.match(response.body,/BOS Integrations/);assert.match(response.body,/WhatsApp/);assert.match(response.body,/CRM/);assert.match(response.body,/Payments/);assert.match(response.body,/Connect/)})
test('serves automation execution surface',async()=>{const response=await request('/execution');assert.equal(response.statusCode,200);assert.match(response.contentType,/text\/html/);assert.match(response.body,/BOS Automation Execution/);assert.match(response.body,/Run automation/);assert.match(response.body,/api\/v1\/automations\/run/)})
test('automation endpoint enforces production persistence',async()=>{const response=await post('/api/v1/automations/run',{steps:[{action:'create_task',input:{title:'Follow up'}}],context:{source:'test'}},{'x-tenant-id':'tenant-test'});assert.ok([200,422].includes(response.statusCode));if(response.statusCode===200){const body=JSON.parse(response.body);assert.equal(body.status,'completed');assert.equal(body.execution.tenantId,'tenant-test');assert.equal(body.execution.results.length,1)}else{const body=JSON.parse(response.body);assert.equal(body.error.code,'AUTOMATION_FAILED')}})
