const crypto = require('node:crypto');
const { jsonResponse } = require('./http');
const { getProductionStore } = require('../../packages/persistence/production_store');
const { encryptSecret, decryptSecret } = require('../../modules/integrations/secret_store');
const { getCatalog, getConnector, testConnector } = require('../../modules/integrations/connector_registry');
function id(prefix) { return `${prefix}_${crypto.randomUUID()}`; }
function clean(v, max = 500) { return String(v ?? '').trim().slice(0, max); }
function fail(message, status = 422) { throw Object.assign(new Error(message), { statusCode: status }); }
async function body(req) { let raw=''; for await (const chunk of req) raw += chunk; if(raw.length>1_000_000) fail('PAYLOAD_TOO_LARGE',413); try{return raw?JSON.parse(raw):{};}catch{fail('INVALID_JSON',400);} }
async function member(pool, workspaceId, userId) { const r=await pool.query('SELECT role,status FROM bos_workspace_members WHERE workspace_id=$1 AND user_id=$2',[workspaceId,userId]); return r.rows[0]||null; }
async function requireMember(auth,pool){ if(!auth?.tenantId) fail('WORKSPACE_REQUIRED',422); const m=await member(pool,auth.tenantId,auth.user.id); if(!m||m.status!=='active') fail('WORKSPACE_ACCESS_DENIED',403); return m; }
async function requireWrite(auth,pool){ const m=await requireMember(auth,pool); if(!['owner','admin'].includes(m.role)) fail('INSUFFICIENT_PERMISSIONS',403); return m; }
async function audit(pool,workspaceId,userId,action,provider,metadata={}) { await pool.query('INSERT INTO bos_audit_logs(id,workspace_id,actor_user_id,action,resource_type,resource_id,metadata) VALUES($1,$2,$3,$4,$5,$6,$7)',[id('audit'),workspaceId,userId,action,'integration',provider,metadata]); }
async function handleIntegrationRoute({req,res,url,auth}) {
  if(!url.startsWith('/api/v1/integrations')) return false;
  if(req.method==='GET' && url==='/api/v1/integrations/catalog') return jsonResponse(res,200,{status:'ok',googleClientId:process.env.GOOGLE_CLIENT_ID||null,integrations:getCatalog().map(x=>({...x,configured:x.mode!=='oauth'||Boolean(process.env.GOOGLE_CLIENT_ID)}))});
  if(!auth) return false;
  const store=await getProductionStore(); if(!store) fail('DATABASE_NOT_CONFIGURED',503); const {pool}=store; const workspaceId=auth.tenantId;
  if(req.method==='GET' && url==='/api/v1/integrations') { await requireMember(auth,pool); const r=await pool.query('SELECT id,provider,status,config,connected_at,updated_at,last_error FROM bos_integrations WHERE workspace_id=$1 ORDER BY provider',[workspaceId]); return jsonResponse(res,200,{status:'ok',integrations:r.rows}); }
  await requireWrite(auth,pool);
  const testMatch=url.match(/^\/api\/v1\/integrations\/([^/]+)\/test$/);
  if(testMatch && req.method==='POST') { const provider=clean(testMatch[1],80); const p=getConnector(provider); if(!p) fail('INTEGRATION_NOT_SUPPORTED',404); const payload=await body(req); let credentials=payload.credentials||null; if(!credentials){const r=await pool.query('SELECT encrypted_credentials,config FROM bos_integrations WHERE workspace_id=$1 AND provider=$2',[workspaceId,provider]); if(!r.rowCount) fail('INTEGRATION_NOT_CONNECTED',404); credentials=Object.fromEntries(Object.entries(r.rows[0].encrypted_credentials||{}).map(([k,v])=>[k,decryptSecret(v)]));} try { const result=await testConnector(provider,credentials,payload.config||{}); await pool.query("UPDATE bos_integrations SET status='connected',last_error=NULL,updated_at=NOW() WHERE workspace_id=$1 AND provider=$2",[workspaceId,provider]); return jsonResponse(res,200,{status:'ok',result}); } catch(error){await pool.query('UPDATE bos_integrations SET status=\'error\',last_error=$3,updated_at=NOW() WHERE workspace_id=$1 AND provider=$2',[workspaceId,provider,clean(error.message,500)]); return jsonResponse(res,422,{status:'error',code:'INTEGRATION_TEST_FAILED',message:error.message});} }
  const providerMatch=url.match(/^\/api\/v1\/integrations\/([^/]+)$/);
  if(providerMatch && req.method==='POST') { const provider=clean(providerMatch[1],80); const connector=getConnector(provider); if(!connector) fail('INTEGRATION_NOT_SUPPORTED',404); const p=await body(req); const supplied=p.credentials&&typeof p.credentials==='object'?p.credentials:{}; for(const field of connector.fields||[]) if(field.required && !clean(supplied[field.key],2000)) fail(`${field.key.toUpperCase()}_REQUIRED`,400); const credentials={}; for(const field of connector.fields||[]) if(supplied[field.key]!==undefined && supplied[field.key]!==null && String(supplied[field.key]).length) credentials[field.key]=String(supplied[field.key]); const result=await testConnector(provider,credentials,p.config||{}); const encrypted=Object.fromEntries(Object.entries(credentials).map(([k,v])=>[k,encryptSecret(v)])); await pool.query(`INSERT INTO bos_integrations(id,workspace_id,provider,encrypted_credentials,config,connected_by,status,connected_at,updated_at,last_error) VALUES($1,$2,$3,$4,$5,$6,'connected',NOW(),NOW(),NULL) ON CONFLICT(workspace_id,provider) DO UPDATE SET encrypted_credentials=EXCLUDED.encrypted_credentials,config=EXCLUDED.config,status='connected',connected_by=EXCLUDED.connected_by,connected_at=NOW(),updated_at=NOW(),last_error=NULL`,[id('integration'),workspaceId,provider,encrypted,p.config||{},auth.user.id]); await audit(pool,workspaceId,auth.user.id,'integration.connected',provider,{account:result.account||null}); return jsonResponse(res,201,{status:'connected',provider,account:result.account||null,result}); }
  if(providerMatch && req.method==='DELETE') { const provider=clean(providerMatch[1],80); await pool.query(`UPDATE bos_integrations SET status='disconnected',encrypted_credentials='{}'::jsonb,updated_at=NOW() WHERE workspace_id=$1 AND provider=$2`,[workspaceId,provider]); await audit(pool,workspaceId,auth.user.id,'integration.disconnected',provider); return jsonResponse(res,200,{status:'disconnected',provider}); }
  return false;
}
module.exports={handleIntegrationRoute};
